title: Bodge - The Idiotic Build System
description: A minimalistic but powerful C++ build system that reads from a simple configuration file
url: https://el-dockerr.github.io
baseurl: "/bodge"

# Theme
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation (handled by theme)

# Repository information
repository: el-dockerr/bodge

# Social
github_username: el-dockerr
github:
  repository_url: https://github.com/el-dockerr/bodge

# SEO
author: Swen "El Dockerr" Kalski
twitter_username: el_dockerr

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Include
include:
  - _pages

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"